export const checklistFields = ['Pneus','Faróis','Vidros','Retrovisores','Lataria','Limpeza','Estepe','Ferramentas','Documentação','Avarias'];
export const photoFields = ['Frontal','Traseira','Lateral direita','Lateral esquerda','Painel'];
export type Actor = { id:string; role:string; driver:string; name:string };
export function emptyState(){return {vehicles:[] as any[],drivers:[] as string[],projects:[] as string[],custody:[] as any[],transfers:[] as any[],checklists:[] as any[],fuel:[] as any[],logs:[] as any[],issues:[] as any[],expenses:[] as any[],maintenance:[] as any[]};}
const fail=(message:string):never=>{throw new Error(message)};
const str=(value:unknown,max=200)=>typeof value==='string'&&value.trim().length>0&&value.trim().length<=max?value.trim():fail('Preencha um texto válido.');
const number=(value:unknown,min:number,max:number)=>{const n=Number(value);return Number.isFinite(n)&&n>=min&&n<=max?n:fail('Informe um número válido.');};
export function transition(previous:any,input:any,actor:Actor,now=new Date().toISOString()){
 const s=structuredClone(previous);const d=input||{};const id=()=>crypto.randomUUID();
 const manager=['Administrador','Gestor de Frota'].includes(actor.role);const admin=actor.role==='Administrador';
 const managersOnly=()=>{if(!manager)fail('Ação exclusiva da gestão.')};
 const driver=()=>{if(!actor.driver||!s.drivers.includes(actor.driver))fail('Sua conta precisa estar vinculada a um condutor cadastrado.');return actor.driver};
 const log=(v:any,kind:string,text:string)=>s.logs.unshift({id:id(),vehicle:v?.id||null,at:now,kind,text,actor:actor.name,actorId:actor.id});
 if(d.action==='addVehicle') {managersOnly();const plate=str(d.plate,7).toUpperCase().replace(/-/g,'');if(!/^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$/.test(plate)||s.vehicles.some((v:any)=>v.plate===plate))fail('Placa inválida ou já cadastrada.');const v={id:id(),token:id(),plate,model:str(d.model,90),km:number(d.km,0,3000000),next:number(d.next,0,3000000),status:'Disponível',daily:'Pendente'};s.vehicles.push(v);log(v,'Cadastro','Veículo cadastrado');return s;}
 if(d.action==='addProject'){managersOnly();const p=str(d.name,100);if(s.projects.includes(p))fail('Obra já cadastrada.');s.projects.push(p);log(null,'Cadastro','Obra cadastrada: '+p);return s;}
 if(d.action==='addDriver'){managersOnly();const name=str(d.name,100);if(s.drivers.includes(name))fail('Condutor já cadastrado.');s.drivers.push(name);log(null,'Cadastro','Condutor cadastrado: '+name);return s;}
 const v=s.vehicles.find((x:any)=>x.id===d.vehicle);if(!v)fail('Veículo não encontrado.');
 const c=s.custody.find((x:any)=>x.vehicle===v.id&&!x.end);
 const t=s.transfers.find((x:any)=>x.vehicle===v.id&&x.status!=='Transferência concluída');
 const own=()=>{if(!c||c.driver!==driver())fail('Apenas o responsável atual pode executar esta ação.')};
 const km=()=>{const n=number(d.km,v.km,3000000);if(!Number.isInteger(n))fail('Quilometragem deve ser inteira.');return n};
 const project=()=>{if(!s.projects.includes(d.project))fail('Selecione uma obra cadastrada.');return d.project};
 const full=()=>{km();if(!['Vazio','¼','½','¾','Cheio'].includes(d.fuelLevel))fail('Informe o nível de combustível.');if(!checklistFields.every(k=>['Regular','Avaria'].includes(d.items?.[k])))fail('Preencha todos os itens do checklist.');if(!photoFields.every(k=>typeof d.photos?.[k]==='string'&&d.photos[k]))fail('As cinco fotos são obrigatórias.');if(Object.values(d.items).includes('Avaria'))str(d.description,1000);};
 if(d.action==='request'){if(!c||c.driver===driver()||t)fail('Transferência indisponível.');s.transfers.push({id:id(),vehicle:v.id,from:c.driver,to:driver(),status:'Transferência solicitada',at:now});log(v,'Transferência','Solicitação: '+c.driver+' → '+actor.driver);}
 else if(d.action==='accept'){own();if(!t||t.status!=='Transferência solicitada')fail('Solicitação indisponível.');t.status='Aguardando entrega';log(v,'Transferência','Entrega aceita');}
 else if(d.action==='beginDelivery'){own();if(t&& !['Aguardando entrega','Checklist de entrega em andamento'].includes(t.status))fail('Aceite a solicitação antes da entrega.');if(t)t.status='Checklist de entrega em andamento';log(v,'Checklist','Entrega iniciada');}
 else if(d.action==='beginReceipt'){driver();if(c||['Bloqueado','Em manutenção'].includes(v.status))fail('Veículo indisponível; o responsável atual deve entregar antes.');if(t){if(t.to!==actor.driver||!['Aguardando recebimento','Checklist de recebimento em andamento'].includes(t.status))fail('Transferência reservada para outro condutor.');t.status='Checklist de recebimento em andamento';}log(v,'Checklist','Recebimento iniciado');}
 else if(d.action==='deliver'){own();full();if(t&&t.status!=='Checklist de entrega em andamento')fail('Inicie o checklist de entrega.');c.end=now;c.endKm=km();v.km=km();v.status=t?'Aguardando transferência':'Disponível';if(t)t.status='Aguardando recebimento';s.checklists.unshift({...d,id:id(),at:now,driver:c.driver,custody:c.id,type:'Entrega'});log(v,'Entrega',c.driver+' entregou · '+v.km+' km');}
 else if(d.action==='receive'){driver();if(c||['Bloqueado','Em manutenção'].includes(v.status))fail('Veículo indisponível.');if(t&&(t.to!==actor.driver||t.status!=='Checklist de recebimento em andamento'))fail('Inicie o recebimento reservado para você.');full();project();str(d.activity,200);const custody={id:id(),vehicle:v.id,driver:actor.driver,project:d.project,activity:d.activity,start:now,end:null,km:km(),segments:[{project:d.project,at:now}]};s.custody.push(custody);v.km=km();v.status='Em uso';v.daily='Regular';v.dailyAt=now;if(t){t.status='Transferência concluída';t.finished=now;}s.checklists.unshift({...d,id:id(),at:now,driver:actor.driver,custody:custody.id,type:'Recebimento'});log(v,'Recebimento',actor.driver+' recebeu · '+d.project);}
 else if(d.action==='force'){managersOnly();str(d.reason,1000);if(d.reason.trim().length<10)fail('Justifique em pelo menos 10 caracteres.');if(!s.drivers.includes(d.newDriver))fail('Selecione um condutor.');project();km();if(c){c.end=now;c.endKm=km();}if(t){t.status='Transferência concluída';t.forced=true;t.finished=now;}s.custody.push({id:id(),vehicle:v.id,driver:d.newDriver,project:d.project,activity:'Transferência administrativa',start:now,end:null,km:km(),segments:[{project:d.project,at:now}]});v.km=km();v.status='Com pendência';v.daily='Pendente';log(v,'Administração','Transferência administrativa: '+d.reason);}
 else if(d.action==='project'){own();project();c.project=d.project;c.segments.push({project:d.project,at:now});log(v,'Obra','Obra alterada para '+d.project);}
 else if(d.action==='daily'){own();km();project();if(!['Sim','Não'].includes(d.normal))fail('Confirme as condições do veículo.');if(d.normal==='Não'){str(d.description,1000);if(!d.problem||!d.photo||!['Baixa','Atenção','Crítica'].includes(d.severity)||!['Sim','Não'].includes(d.circulate))fail('Informe problema, gravidade e foto.');}if(c.project!==d.project){c.project=d.project;c.segments.push({project:d.project,at:now});log(v,'Obra','Obra alterada para '+d.project);}v.km=km();v.daily='Regular';v.dailyAt=now;s.checklists.unshift({...d,id:id(),at:now,driver:c.driver,custody:c.id,type:'Diário'});if(d.normal==='Não'){s.issues.unshift({...d,id:id(),at:now,driver:c.driver});if(d.severity==='Crítica'||d.circulate==='Não')v.status='Bloqueado';log(v,'Alerta','Ocorrência: '+d.description);}log(v,'Checklist','Checklist diário · '+v.km+' km');}
 else if(d.action==='fuel'){own();km();const liters=number(d.liters,0.01,2000),total=number(d.total,0.01,100000);str(d.station,120);if(!d.receipt||!['Gasolina','Etanol','Diesel S10'].includes(d.fuel))fail('Inclua o cupom e o tipo de combustível.');const history=s.fuel.filter((f:any)=>f.vehicle===v.id);const previousFull=history.findIndex((f:any)=>f.full);const anchor=previousFull>=0?history[previousFull]:null;const since=anchor?history.slice(0,previousFull):[];const distance=anchor?km()-anchor.km:0;const supplied=liters+since.reduce((n:number,f:any)=>n+f.liters,0);const paid=total+since.reduce((n:number,f:any)=>n+f.total,0);const consumption=anchor&&d.full&&distance>0?distance/supplied:null;const avg=history.filter((f:any)=>f.consumption).map((f:any)=>f.consumption);const baseline=avg.length?avg.reduce((a:number,b:number)=>a+b,0)/avg.length:null;s.fuel.unshift({...d,id:id(),at:now,driver:c.driver,project:c.project,custody:c.id,km:km(),liters,total,consumption,costKm:consumption?paid/distance:null,variation:consumption&&baseline?(consumption/baseline-1)*100:null});v.km=km();log(v,'Abastecimento',liters+' litros · R$ '+total.toFixed(2));}
 else if(d.action==='expense'){managersOnly();if(!['Pedágio','Multa'].includes(d.kind))fail('Tipo inválido.');const at=new Date(d.at);if(!Number.isFinite(at.getTime())||at.getTime()>Date.now()+60000)fail('Data inválida.');const amount=number(d.amount,0.01,1000000);const holder=s.custody.find((x:any)=>x.vehicle===v.id&&x.start<=at.toISOString()&&(!x.end||x.end>at.toISOString()));const segment=holder?.segments.filter((x:any)=>x.at<=at.toISOString()).at(-1);s.expenses.unshift({id:id(),vehicle:v.id,kind:d.kind,at:at.toISOString(),amount,location:str(d.location,200),reference:str(d.reference,120),driver:holder?.driver||null,project:segment?.project||null,registeredAt:now,actorId:actor.id});log(v,d.kind,d.reference+' · R$ '+amount.toFixed(2));}
 else if(d.action==='maintenance'){managersOnly();const next=number(d.next,v.km,3000000);s.maintenance.unshift({id:id(),vehicle:v.id,at:now,km:km(),next,description:str(d.description,300),amount:number(d.amount,0,1000000),actorId:actor.id});v.km=km();v.next=next;v.status=c?'Em uso':'Disponível';log(v,'Manutenção','Serviço registrado: '+d.description);}
 else fail('Ação não reconhecida.');
 const active=s.custody.filter((x:any)=>!x.end);if(new Set(active.map((x:any)=>x.vehicle)).size!==active.length)fail('Conflito de posse. Atualize os dados.');return s;
}
