import {test} from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,transition,checklistFields,photoFields} from '../supabase/functions/_shared/domain.ts';
const joao={id:'u1',role:'Condutor',driver:'João',name:'João'};
const maria={id:'u2',role:'Condutor',driver:'Maria',name:'Maria'};
const manager={id:'u3',role:'Gestor de Frota',driver:'',name:'Gestora'};
const full={km:120,project:'Obra 1',activity:'Atendimento',fuelLevel:'Cheio',items:Object.fromEntries(checklistFields.map(k=>[k,'Regular'])),photos:Object.fromEntries(photoFields.map(k=>[k,'foto']))};
function setup(){let s:any=emptyState();s=transition(s,{action:'addDriver',name:'João'},manager);s=transition(s,{action:'addDriver',name:'Maria'},manager);s=transition(s,{action:'addProject',name:'Obra 1'},manager);s=transition(s,{action:'addVehicle',plate:'ABC1D23',model:'Utilitário',km:100,next:10000},manager);return s;}
test('entrega antes de recebimento e sem sobreposição de posse',()=>{let s=setup();const vehicle=s.vehicles[0].id;s=transition(s,{...full,action:'receive',vehicle},joao);assert.throws(()=>transition(s,{...full,action:'receive',vehicle},maria),/indisponível/);s=transition(s,{action:'request',vehicle},maria);assert.throws(()=>transition(s,{...full,action:'deliver',vehicle},maria),/responsável atual/);s=transition(s,{action:'accept',vehicle},joao);s=transition(s,{action:'beginDelivery',vehicle},joao);s=transition(s,{...full,action:'deliver',vehicle},joao);s=transition(s,{action:'beginReceipt',vehicle},maria);s=transition(s,{...full,action:'receive',vehicle,km:121},maria);assert.equal(s.custody.filter((c:any)=>!c.end).length,1);assert.equal(s.custody.at(-1).driver,'Maria');});
test('condutor não altera posse de outro e km não retrocede',()=>{let s=setup();const vehicle=s.vehicles[0].id;s=transition(s,{...full,action:'receive',vehicle},joao);assert.throws(()=>transition(s,{action:'daily',vehicle,km:119,project:'Obra 1',normal:'Sim'},joao),/número válido/);assert.throws(()=>transition(s,{action:'force',vehicle,km:120,project:'Obra 1',newDriver:'Maria',reason:'Transferência justificada'},maria),/gestão/);});
test('pedágio vincula obra no instante do evento',()=>{let s=setup();const vehicle=s.vehicles[0].id;s=transition(s,{...full,action:'receive',vehicle},joao,'2026-09-24T10:00:00Z');s=transition(s,{action:'expense',vehicle,kind:'Pedágio',at:'2026-09-24T12:00:00Z',amount:14.5,location:'BR-153',reference:'Fatura 1'},manager);assert.equal(s.expenses[0].driver,'João');assert.equal(s.expenses[0].project,'Obra 1');});
test('consumo soma abastecimentos parciais entre tanques cheios',()=>{let s=setup();const vehicle=s.vehicles[0].id;s=transition(s,{...full,action:'receive',vehicle},joao);const fuel=(km:number,liters:number,full:boolean)=>({action:'fuel',vehicle,km,liters,total:liters*6,station:'Posto',receipt:'foto',fuel:'Diesel S10',full});s=transition(s,fuel(120,10,true),joao);s=transition(s,fuel(220,5,false),joao);s=transition(s,fuel(320,15,true),joao);assert.equal(s.fuel[0].consumption,10);assert.equal(s.fuel[0].costKm,0.6);});
