import {useState,useEffect,useCallback} from 'react';
import type {FormEvent} from 'react';
import type {Session} from '@supabase/supabase-js';
import Dashboard from './Dashboard';
import Operations from '../app/operations';
import {Toaster,toast} from 'sonner';
import {Truck,LayoutDashboard,Map,Users,ArrowLeftRight,ClipboardCheck,Fuel,Wrench,Receipt,ShieldAlert,Award,ChartNoAxesCombined,Settings,QrCode,ChevronRight,Bell,LogOut,WifiOff} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarTrigger} from '@/components/ui/sidebar';
import {emptyState} from '@/supabase/functions/_shared/domain';
import {configured,supabase,fleetRequest} from './backend';
const menu=[['Dashboard',LayoutDashboard],['Central da Frota',Map],['Veículos',Truck],['Condutores',Users],['Transferência de Posse',ArrowLeftRight],['Checklists',ClipboardCheck],['Abastecimento',Fuel],['Manutenção',Wrench],['Pedágios',Receipt],['Multas',ShieldAlert],['Bonificação',Award],['Relatórios',ChartNoAxesCombined],['Configurações',Settings]] as const;
export default function FleetApp(){
 const [session,setSession]=useState<Session|null>(null),[passwordSetup,setPasswordSetup]=useState(location.hash.includes('type=invite')||location.hash.includes('type=recovery')),[authLoading,setAuthLoading]=useState(true),[page,setPage]=useState('Dashboard'),[state,setState]=useState<any>(emptyState()),[version,setVersion]=useState(0),[org,setOrg]=useState(''),[ready,setReady]=useState(false),[error,setError]=useState(''),[selected,setSelectedState]=useState(''),[online,setOnline]=useState(navigator.onLine);
 const setSelected=(id:string)=>{setSelectedState(id);const u=new URL(location.href);u.searchParams.set('veiculo',id);u.searchParams.delete('qr');history.replaceState(null,'',u)};
 const navigate=(p:string)=>{setPage(p);location.hash=encodeURIComponent(p)};
 const refresh=useCallback(async()=>{try{const d=await fleetRequest('GET');setState(d.state);setVersion(d.version);setOrg(d.organizationId);setReady(true);setError('');const params=new URLSearchParams(location.search);const found=d.state.vehicles.find((v:any)=>v.token===params.get('qr'));if(found){setSelected(found.id);navigate('Detalhes do Veículo')}else setSelectedState(current=>d.state.vehicles.some((v:any)=>v.id===current)?current:(d.state.vehicles.find((v:any)=>v.id===params.get('veiculo'))?.id||d.state.vehicles[0]?.id||''))}catch(e:any){setError(e.message);setReady(false)}},[]);
 useEffect(()=>{supabase.auth.getSession().then(({data}:any)=>{setSession(data.session);setAuthLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event:string,s:Session|null)=>{setSession(s);if(!s){setState(emptyState());setReady(false);setOrg('')}});const h=()=>setOnline(navigator.onLine);window.addEventListener('online',h);window.addEventListener('offline',h);return()=>{subscription.unsubscribe();window.removeEventListener('online',h);window.removeEventListener('offline',h)}},[]);
 useEffect(()=>{if(!session)return;refresh();const n=setInterval(()=>{if(navigator.onLine)refresh()},30000);return()=>clearInterval(n)},[session?.user.id,refresh]);
 useEffect(()=>{const h=()=>{const value=decodeURIComponent(location.hash.slice(1));if(menu.some(([name])=>name===value)||['Motorista','Detalhes do Veículo','Scanner QR Code','Checklist Diário','Entrega do Veículo','Recebimento do Veículo','Detalhes do Condutor'].includes(value))setPage(value)};h();window.addEventListener('hashchange',h);return()=>window.removeEventListener('hashchange',h)},[]);
 async function act(data:any){if(!online)throw new Error('Conecte-se para registrar esta ação.');try{const d=await fleetRequest('POST',{...data,version});setState(d.state);setVersion(d.version);toast.success('Registro salvo.');return d.state}catch(e:any){if(e.status===409)await refresh();throw e}}
 if(!configured)return <div className="auth-screen"><div className="auth-card"><h1>Vialink</h1><p>Configure VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY para iniciar.</p></div></div>;
 if(authLoading)return <div className="auth-screen">Carregando Vialink…</div>;
 if(!session)return <Login/>;
 if(passwordSetup)return <SetPassword onDone={()=>{setPasswordSetup(false);history.replaceState(null,'',location.pathname)}}/>;
 return <SidebarProvider><Sidebar><SidebarHeader><div className="brand"><span><Truck size={23}/></span>vialink.</div><div className="workspace">GESTÃO DA FROTA</div></SidebarHeader><SidebarContent><nav>{menu.filter(([name])=>state.role!=='Condutor'||['Veículos','Transferência de Posse','Checklists','Abastecimento'].includes(name)).map(([name,Icon])=><button key={name} className={page===name?'nav-item active':'nav-item'} onClick={()=>navigate(name)}><Icon size={18}/>{name}</button>)}</nav></SidebarContent><SidebarFooter><button className="driver-switch" onClick={()=>navigate('Motorista')}><QrCode size={19}/> Visão do motorista</button><div className="profile"><b>{(state.userName||session.user.email||'U').slice(0,2).toUpperCase()}</b><div>{state.userName||session.user.email}<small>{state.role||'Aguardando vínculo'}</small></div></div><button className="btn" onClick={()=>supabase.auth.signOut()}><LogOut size={16}/> Sair</button></SidebarFooter></Sidebar><main className="main"><header className="topbar"><div><SidebarTrigger/><span>Vialink</span><ChevronRight size={14}/><strong>{page}</strong></div><div>{!online&&<span className="offline"><WifiOff size={16}/> Sem conexão</span>}<button aria-label="Ver alertas" onClick={()=>navigate('Manutenção')}><Bell size={19}/></button></div></header><div className="content"><div className={page==='Motorista'?'page-heading driver-hidden':'page-heading'}><div><div className="eyebrow">{new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).toUpperCase()}</div><h1>{page==='Dashboard'?'Visão geral da frota':page}</h1>{page==='Dashboard'&&<p>Acompanhe os registros da operação.</p>}</div></div>{error&&<div className="notice" role="alert">{error} <button onClick={refresh}>Tentar novamente</button></div>}{!online&&<div className="notice" role="status">Conecte-se para consultar dados atualizados e registrar operações.</div>}{ready&&(page==='Dashboard'?<Dashboard state={state} setPage={navigate}/>:<Operations page={page} navigate={navigate} state={state} act={act} selected={selected} setSelected={setSelected} ready={ready} organizationId={org} userId={session.user.id}/>)}<Toaster position="bottom-center"/><footer className="page-footer"><span>VIALINK · GESTÃO DA FROTA</span><span>Posse registrada. Operação rastreável.</span></footer></div><nav className="mobile-nav" aria-label="Navegação principal">{[['Início','Dashboard',LayoutDashboard],['Veículos','Veículos',Truck],['Ler QR','Scanner QR Code',QrCode],['Checklists','Checklists',ClipboardCheck],['Minha área','Motorista',Users]].map(([label,target,Icon]:any)=><button key={label} className={page===target?'active':''} onClick={()=>navigate(target)}><Icon size={21}/><span>{label}</span></button>)}</nav></main></SidebarProvider>;
}
function Login(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[mode,setMode]=useState<'login'|'signup'|'reset'|'newPassword'>('login'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(location.hash.includes('type=invite')||location.hash.includes('type=recovery'))setMode('newPassword')},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{let error:any=null;if(mode==='login')({error}=await supabase.auth.signInWithPassword({email,password}));if(mode==='signup')({error}=await supabase.auth.signUp({email,password,options:{data:{name},emailRedirectTo:location.origin}}));if(mode==='reset')({error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin}));if(mode==='newPassword')({error}=await supabase.auth.updateUser({password}));if(error)throw error;setMessage(mode==='signup'?'Conta criada. Verifique seu e-mail e solicite o vínculo à empresa.':mode==='reset'?'Confira seu e-mail.':mode==='newPassword'?'Senha definida. Entre com seu e-mail.':'Entrando…');if(mode==='newPassword'){await supabase.auth.signOut();setMode('login')}}catch(e:any){setMessage(e.message||'Não foi possível entrar.')}finally{setBusy(false)}}
 return <div className="auth-screen"><form className="auth-card" onSubmit={submit}><div className="brand"><span><Truck size={24}/></span>vialink.</div><h1>{mode==='login'?'Acesse sua frota':mode==='signup'?'Crie sua conta':mode==='reset'?'Recupere o acesso':'Defina sua senha'}</h1><p>Veículos, checklists e responsabilidade em um só lugar.</p>{mode==='signup'&&<label>Nome<input required value={name} onChange={e=>setName(e.target.value)}/></label>}{mode!=='newPassword'&&<label>E-mail<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}{mode!=='reset'&&<label>Senha<input type="password" minLength={8} autoComplete={mode==='login'?'current-password':'new-password'} required value={password} onChange={e=>setPassword(e.target.value)}/></label>}{message&&<p role="status" className="notice">{message}</p>}<button type="submit" className="btn primary" disabled={busy}>{busy?'Aguarde…':mode==='login'?'Entrar':mode==='signup'?'Criar conta':mode==='reset'?'Enviar e-mail':'Salvar senha'}</button><div className="auth-links">{mode!=='login'&&<button type="button" onClick={()=>setMode('login')}>Voltar ao login</button>}{mode==='login'&&<><button type="button" onClick={()=>setMode('signup')}>Criar conta</button><button type="button" onClick={()=>setMode('reset')}>Esqueci a senha</button></>}</div></form></div>;
}
function SetPassword({onDone}:{onDone:()=>void}){const [password,setPassword]=useState(''),[message,setMessage]=useState('');return <div className="auth-screen"><form className="auth-card" onSubmit={async e=>{e.preventDefault();const {error}=await supabase.auth.updateUser({password});if(error)setMessage(error.message);else onDone()}}><h1>Defina sua senha</h1><label>Nova senha<input type="password" minLength={8} required autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{message&&<p role="alert">{message}</p>}<button className="btn primary">Salvar senha</button></form></div>}
